---
# handlers file for prob
- name: Restart apache
  service: 
    name: apache2 
    state: restarted

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Restart PHP5-FPM
  service:
    name: php5-fpm
    state: restarted
